# coding: utf-8

GENERATOR: dict = {
    "TARGET": {
        "COUNTRY": "FRANCE",
        "OPTIONS": {
            "DESK": False,
            "MOBILE": True
        }
    },

    "NDIGITS": "{BUILDER::ARTEFACT}",
    "SAME_DIGIT_THRESHOLD": "{BUILDER::ARTEFACT}",
    "CONSECUTIVE_SAME_DIGIT_THRESHOLD": "{BUILDER::ARTEFACT}",
    "LAST_BLOCK_HEAD_MAX_ZEROS": "{BUILDER::ARTEFACT}",
    "BANNED_OPERATOR_CODES": "{BUILDER::ARTEFACT}",
    "PREFIX_DATA": "{BUILDER::ARTEFACT}"
}
